version: '2'
services:
  project_db:
    image: mysql:5.7
    container_name: project_mysql
    network_mode: "bridge"
    volumes:
      - "project_database_data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    expose:
      - "3306"
    environment:
      DNSDOCK_NAME: db
      DNSDOCK_IMAGE: project
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_db_user
      MYSQL_PASSWORD: my_db_password
  project_php:
    depends_on:
      - project_db
    build: ./php
    container_name: project_php
    links:
      - project_db
    volumes:
      - "./php/etc:/usr/local/etc"
      - "../site:/var/www/site"
      - "./logs/php:/var/log/php"
    expose:
      - "9000"
    working_dir: "/var/www/site"
  project_nginx:
      depends_on:
        - project_php
      image: nginx
      container_name: project_nginx
      network_mode: "bridge"
      ports:
        - "80:80"
      links:
        - project_php
      volumes:
        - "./nginx/etc:/etc/nginx"
        - "../site:/var/www/site"
        - "./logs/nginx:/var/log/nginx"
      working_dir: "/var/www/site"
      environment:
        DNSDOCK_NAME: site
        DNSDOCK_IMAGE: project
volumes:
  project_database_data:
    driver: local
