version: '2'
services:
  project_db:
    image: mysql:5.7
    container_name: project_db 
    expose:
      - "3306"
    volumes:
      - "project_database_data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db 
      MYSQL_USER: p_db_user
      MYSQL_PASSWORD: p<A$EXMnB2JMfx`V
  project_php:
    depends_on:
      - project_db
    build: ./php
    container_name: project_php
    expose:
      - "9000"
    volumes:
      - "./php/etc:/usr/local/etc"
      - "../site:/var/www/site"
      - "./logs/php:/var/log/php"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: project_db
      DB_PORT: 3306        
      DB_DATABASE: project_db
      DB_USERNAME: p_db_user
      DB_PASSWORD: p<A$EXMnB2JMfx`V  
    working_dir: "/var/www/site"
  project_nginx:
      depends_on:
        - project_php
      image: nginx
      ports:
        - "80:80"
      container_name: project_nginx
      volumes:
        - "./nginx/etc:/etc/nginx"
        - "../site:/var/www/site"
        - "./logs/nginx:/var/log/nginx"
      working_dir: "/var/www/site"
volumes:
  project_database_data:
    driver: local
